[package]
name = "oxidiser"
version = "0.1.0"
authors = ["Mițca Dumitru <dumitru0mitca@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxidiser-models = { path = "oxidiser-models" }

[workspace]
members = ["oxidiser-models"]
