[package]
name = "oxidiser"
version = "0.1.0"
authors = ["Mițca Dumitru <dumitru0mitca@gmail.com>"]
edition = "2018"

[dependencies]
oxidiser-models = { path = "oxidiser-models" }

tracing = "0.1"
tracing-subscriber = "0.2"

serde_json = "1.0.60"

[workspace]
members = ["oxidiser-models"]
